/**
 * backend/blockResolution/ocrKeywordBank.js  — V2
 *
 * Three-tier keyword structure per subject/section:
 *   phraseWeights      — exact multi-word phrases (highest signal)
 *   rareKeywordWeights — rare domain-specific single tokens (high signal)
 *   keywordWeights     — common keywords (moderate signal)
 *
 * Also exports SECTION_ALIASES to normalize OCR variant labels
 * to canonical pdfToSyllabusMap.js section keys.
 */

// ─── SECTION ALIASES ─────────────────────────────────────────────────────────
// Maps OCR/colloquial variants → exact section name in SECTION_KEYWORDS / pdfToSyllabusMap

export const SECTION_ALIASES = {
  // Polity
  "fundamental right": "Fundamental Rights",
  "fundamental rights and duties": "Fundamental Rights",
  "writs and remedies": "Fundamental Rights",
  "judicial system": "Judiciary",
  "supreme court jurisdiction": "Judiciary",
  "high court jurisdiction": "Judiciary",
  "pil": "Judiciary",
  "public interest litigation": "Judiciary",
  "center state": "Federalism and Center-State Relations",
  "centre state relations": "Federalism and Center-State Relations",
  "seventh schedule": "Federalism and Center-State Relations",
  "constitutional body": "Constitutional Bodies",
  "election commission of india": "Constitutional Bodies",
  "cag audit": "Constitutional Bodies",
  "local body": "Local Self Government",
  "panchayati raj": "Local Self Government",
  "73rd amendment": "Local Self Government",
  "74th amendment": "Local Self Government",

  // Economy
  "monetary policy committee": "Monetary Policy and RBI",
  "reserve bank": "Monetary Policy and RBI",
  "rbi policy": "Monetary Policy and RBI",
  "repo rate policy": "Monetary Policy and RBI",
  "price index": "Inflation and Price Indices",
  "cpi wpi": "Inflation and Price Indices",
  "consumer price": "Inflation and Price Indices",
  "fiscal policy": "Budget and Fiscal Policy",
  "union budget": "Budget and Fiscal Policy",
  "frbm": "Budget and Fiscal Policy",
  "capital market": "Financial Markets and Capital Market",
  "stock market": "Financial Markets and Capital Market",
  "external sector": "External Sector and BOP",
  "balance of payment": "External Sector and BOP",
  "forex reserve": "External Sector and BOP",

  // Environment
  "biodiversity convention": "International Environmental Conventions",
  "climate conventions": "International Environmental Conventions",
  "environmental treaty": "International Environmental Conventions",
  "ramsar wetland": "International Environmental Conventions",
  "protected area": "Conservation and Protected Areas",
  "tiger reserve": "Conservation and Protected Areas",
  "national park wildlife": "Conservation and Protected Areas",
  "ecosystem ecology": "Ecology Concepts",
  "food chain web": "Ecology Concepts",
  "species conservation": "Species Conservation",
  "iucn list": "Species Conservation",
  "endangered species": "Species Conservation",
  "environmental law": "Environmental Legislation and Acts",
  "eia process": "Environmental Legislation and Acts",

  // Science & Technology
  "space technology": "Space",
  "satellite technology": "Space",
  "isro mission": "Space",
  "rocket launch": "Space",
  "gene therapy": "Biotechnology",
  "crispr editing": "Biotechnology",
  "gmo crop": "Biotechnology",
  "nuclear power": "Nuclear Technology",
  "atomic energy": "Nuclear Technology",
  "artificial intelligence ml": "AI and Emerging Technology",
  "quantum computing": "AI and Emerging Technology",
  "cyber security": "IT and Communications",
  "5g network": "IT and Communications",
  "missile defense": "Defence Technology",
  "ballistic missile": "Defence Technology",
  "monoclonal antibody": "Biotechnology",
  "vaccine development": "Health and Diseases",

  // Geography
  "river system": "Rivers and Drainage",
  "drainage basin": "Rivers and Drainage",
  "river interlinking": "Rivers and Drainage",
  "indian climate": "Indian Climate and Monsoon",
  "monsoon system": "Indian Climate and Monsoon",
  "western disturbance": "Indian Climate and Monsoon",
  "pressure belt": "Physical Geography - Climatology",
  "jet stream": "Physical Geography - Climatology",
  "climate zone": "Physical Geography - Climatology",
  "plate tectonic": "Physical Geography - Geomorphology",
  "rock formation": "Physical Geography - Geomorphology",
  "landform erosion": "Physical Geography - Geomorphology",
  "ocean currents": "Oceanography",
  "continental shelf": "Oceanography",
  "eez zone": "Oceanography",
  "physiography india": "Indian Physiography",
  "himalayan range": "Indian Physiography",
  "deccan plateau": "Indian Physiography",

  // Medieval History
  "iqta administration": "Delhi Sultanate",
  "slave dynasty": "Delhi Sultanate",
  "sultanate administration": "Delhi Sultanate",
  "mansabdari system": "Mughal Empire",
  "mughal administration": "Mughal Empire",
  "bhakti saints": "Bhakti and Sufi Movements",
  "sufi orders": "Bhakti and Sufi Movements",

  // Modern History
  "cabinet mission plan": "Partition and Independence",
  "mountbatten plan": "Partition and Independence",
  "freedom movement": "Nationalist Movement",
  "independence movement": "Nationalist Movement",
  "civil disobedience movement": "Nationalist Movement",
  "non cooperation": "Nationalist Movement",
  "quit india movement": "Nationalist Movement",

  // International Relations
  "regional grouping": "Regional Groupings",
  "multilateral grouping": "Regional Groupings",
  "bimstec summit": "Regional Groupings",
  "brics nations": "Regional Groupings",

  // Art & Culture
  "classical dance form": "Performing Arts",
  "folk dance": "Performing Arts",
  "temple style": "Architecture",
  "rock cut architecture": "Architecture",
};

// ─── SUBJECT KEYWORD BANKS V2 ─────────────────────────────────────────────────

export const SUBJECT_KEYWORDS = {

  "Polity": {
    phraseWeights: {
      "fundamental rights": 18,
      "article 19": 20,
      "article 21": 18,
      "article 14": 16,
      "article 32": 18,
      "writ jurisdiction": 18,
      "habeas corpus": 16,
      "mandamus": 14,
      "constituent assembly": 14,
      "constitutional amendment": 16,
      "directive principles": 16,
      "dpsp": 14,
      "right to equality": 14,
      "right to freedom": 14,
      "reasonable restriction": 16,
      "judicial review": 14,
      "public interest litigation": 14,
      "president of india": 12,
      "council of ministers": 12,
      "election commission": 12,
      "center state relations": 14,
      "federalism": 12,
      "lok sabha": 12,
      "rajya sabha": 12,
      "preamble": 12,
      "governor general": 10,
      "emergency provisions": 12,
      "fundamental duties": 14,
      "separation of powers": 12,
      "national emergency": 14,
      "president rule": 14,
      "panchayati raj": 14,
      "73rd amendment": 14,
      "74th amendment": 14,
    },
    rareKeywordWeights: {
      "lokpal": 14,
      "ordinance": 10,
      "writ": 12,
      "dpsp": 14,
      "prorogation": 12,
      "dissolution": 10,
      "delimitation": 12,
      "viceregal": 10,
    },
    keywordWeights: {
      "constitution": 6,
      "parliament": 6,
      "governor": 6,
      "president": 5,
      "amendment": 6,
      "judiciary": 7,
      "rights": 5,
      "elections": 6,
      "bill": 4,
      "panchayat": 7,
      "municipality": 6,
      "speaker": 5,
      "article": 4,
    },
  },

  "Economy": {
    phraseWeights: {
      "repo rate": 18,
      "reverse repo": 16,
      "monetary policy": 16,
      "fiscal policy": 14,
      "balance of payments": 16,
      "current account deficit": 16,
      "open market operations": 14,
      "statutory liquidity ratio": 14,
      "cash reserve ratio": 14,
      "monetary policy committee": 18,
      "goods and services tax": 14,
      "national income": 10,
      "gross domestic product": 12,
      "five year plan": 10,
      "financial inclusion": 12,
      "priority sector lending": 14,
      "fiscal deficit": 14,
      "capital account": 12,
      "foreign exchange reserves": 14,
      "minimum support price": 14,
    },
    rareKeywordWeights: {
      "mpc": 16,
      "rbi": 14,
      "repo": 14,
      "slr": 12,
      "crr": 12,
      "frbm": 14,
      "npa": 12,
      "bop": 14,
      "cad": 12,
      "nbfc": 12,
      "sebi": 12,
      "disinvestment": 10,
    },
    keywordWeights: {
      "inflation": 8,
      "gst": 8,
      "budget": 7,
      "fiscal": 7,
      "banking": 6,
      "forex": 8,
      "gdp": 7,
      "liquidity": 7,
      "subsidy": 6,
      "taxation": 6,
      "deficit": 6,
      "revenue": 5,
      "growth": 4,
    },
  },

  "Environment": {
    phraseWeights: {
      "biodiversity hotspot": 20,
      "endemic species": 16,
      "protected area": 16,
      "national park": 14,
      "wildlife sanctuary": 14,
      "biosphere reserve": 16,
      "climate change": 14,
      "global warming": 14,
      "greenhouse gas": 14,
      "carbon emission": 14,
      "paris agreement": 16,
      "kyoto protocol": 16,
      "ramsar convention": 16,
      "cites convention": 16,
      "environmental impact assessment": 16,
      "ecological footprint": 14,
      "trophic level": 14,
      "keystone species": 14,
      "iucn red list": 16,
      "critically endangered": 14,
      "food web": 12,
      "food chain": 12,
    },
    rareKeywordWeights: {
      "unfccc": 14,
      "ramsar": 14,
      "cites": 14,
      "cbd": 12,
      "iucn": 14,
      "endemic": 12,
      "eia": 10,
      "wetland": 12,
      "mangrove": 12,
      "desertification": 12,
    },
    keywordWeights: {
      "biodiversity": 10,
      "species": 7,
      "ecosystem": 7,
      "ecology": 7,
      "pollution": 6,
      "conservation": 7,
      "habitat": 7,
      "coral": 7,
      "tiger": 5,
      "sanctuary": 6,
    },
  },

  "Science & Technology": {
    phraseWeights: {
      "artificial intelligence": 14,
      "machine learning": 14,
      "gene editing": 18,
      "crispr cas9": 20,
      "recombinant dna": 16,
      "quantum computing": 16,
      "geostationary orbit": 18,
      "polar orbit": 14,
      "launch vehicle": 14,
      "isro mission": 16,
      "nuclear fission": 14,
      "nuclear fusion": 14,
      "stem cell": 14,
      "monoclonal antibody": 16,
      "antimicrobial resistance": 14,
      "ballistic missile": 14,
      "5g technology": 14,
      "internet of things": 14,
      "blockchain technology": 12,
    },
    rareKeywordWeights: {
      "isro": 16,
      "crispr": 16,
      "pslv": 14,
      "gslv": 14,
      "chandrayaan": 14,
      "drdo": 14,
      "genome": 12,
      "nanotechnology": 12,
      "semiconductor": 12,
      "quantum": 10,
      "cybersecurity": 12,
    },
    keywordWeights: {
      "satellite": 7,
      "vaccine": 6,
      "biotechnology": 8,
      "ai": 5,
      "robotics": 7,
      "nuclear": 6,
      "gene": 7,
      "radar": 6,
      "drone": 5,
      "laser": 5,
    },
  },

  "Geography": {
    phraseWeights: {
      "plate tectonics": 16,
      "rock cycle": 14,
      "indian monsoon": 16,
      "southwest monsoon": 16,
      "northeast monsoon": 14,
      "river drainage": 14,
      "watershed management": 12,
      "physiographic division": 16,
      "western ghats": 12,
      "eastern ghats": 12,
      "ocean current": 14,
      "continental shelf": 14,
      "pressure belt": 14,
      "trade winds": 12,
      "jet stream": 12,
      "western disturbance": 16,
      "exclusive economic zone": 14,
      "drainage pattern": 14,
    },
    rareKeywordWeights: {
      "monsoon": 14,
      "physiography": 14,
      "climatology": 12,
      "landform": 12,
      "eez": 14,
      "salinity": 12,
      "estuary": 10,
      "glacier": 10,
    },
    keywordWeights: {
      "drainage": 8,
      "river": 6,
      "soil": 6,
      "ocean": 6,
      "mineral": 5,
      "earthquake": 6,
      "volcano": 6,
      "cyclone": 6,
      "plateau": 6,
      "delta": 6,
      "latitude": 5,
      "longitude": 5,
    },
  },

  "Ancient Indian History": {
    phraseWeights: {
      "indus valley": 20,
      "harappan civilisation": 20,
      "vedic period": 16,
      "rig veda": 14,
      "mauryan empire": 18,
      "ashoka edicts": 18,
      "gupta empire": 16,
      "sangam age": 18,
      "mahajanapada": 16,
      "post mauryan": 12,
      "kushana empire": 12,
    },
    rareKeywordWeights: {
      "harappa": 16,
      "ivc": 16,
      "vedic": 14,
      "maurya": 14,
      "ashoka": 12,
      "gupta": 12,
      "sangam": 14,
      "arthashastra": 14,
      "chandragupta": 12,
      "prehistoric": 10,
      "neolithic": 10,
    },
    keywordWeights: {
      "jain": 6,
      "buddhism": 6,
      "veda": 8,
      "upanishad": 8,
      "aryan": 6,
    },
  },

  "Medieval Indian History": {
    phraseWeights: {
      "delhi sultanate": 20,
      "mughal empire": 18,
      "bhakti movement": 18,
      "sufi movement": 18,
      "iqta system": 20,
      "mansabdari system": 18,
      "jagir": 14,
      "vijayanagara empire": 18,
      "slave dynasty": 16,
      "khilji dynasty": 14,
      "tughlaq dynasty": 14,
    },
    rareKeywordWeights: {
      "mughal": 14,
      "sultanate": 14,
      "bhakti": 12,
      "sufi": 12,
      "iqta": 16,
      "vijayanagara": 14,
      "mansab": 12,
      "akbar": 10,
      "aurangzeb": 10,
      "khilji": 12,
      "tughlaq": 12,
    },
    keywordWeights: {
      "maratha": 6,
      "chola": 7,
      "babar": 7,
      "humayun": 7,
      "lodhi": 6,
    },
  },

  "Modern Indian History": {
    phraseWeights: {
      "freedom struggle": 14,
      "nationalist movement": 14,
      "revolt of 1857": 18,
      "indian national congress": 16,
      "non cooperation movement": 18,
      "civil disobedience": 16,
      "quit india": 18,
      "salt satyagraha": 16,
      "government of india act": 14,
      "cabinet mission": 18,
      "mountbatten plan": 16,
      "partition of india": 14,
      "doctrine of lapse": 14,
    },
    rareKeywordWeights: {
      "satyagraha": 12,
      "swadeshi": 12,
      "viceroy": 10,
      "moderates": 12,
      "extremists": 12,
      "1857": 14,
      "dalhousie": 12,
      "montagu": 12,
      "morley": 10,
    },
    keywordWeights: {
      "gandhi": 9,
      "nehru": 8,
      "tilak": 8,
      "colonial": 6,
      "british": 5,
      "congress": 6,
      "partition": 7,
      "independence": 5,
    },
  },

  "Art & Culture": {
    phraseWeights: {
      "classical dance": 14,
      "folk dance": 12,
      "cave paintings": 16,
      "ajanta caves": 16,
      "ellora caves": 16,
      "temple architecture": 14,
      "stupa architecture": 14,
      "school of painting": 14,
      "miniature painting": 14,
      "geographical indication": 14,
      "gi tag": 14,
      "rock cut": 14,
      "nagara style": 14,
      "dravidian style": 14,
      "bharatanatyam": 14,
      "carnatic music": 12,
      "hindustani music": 12,
    },
    rareKeywordWeights: {
      "stupa": 12,
      "ajanta": 12,
      "ellora": 12,
      "miniature": 12,
      "fresco": 12,
      "numismatic": 12,
      "bharatanatyam": 14,
      "kathak": 12,
    },
    keywordWeights: {
      "architecture": 7,
      "temple": 7,
      "dance": 6,
      "music": 5,
      "painting": 7,
      "sculpture": 7,
      "cave": 7,
      "heritage": 6,
      "literature": 5,
      "theatre": 6,
    },
  },

  "International Relations": {
    phraseWeights: {
      "bilateral relations": 14,
      "strategic partnership": 14,
      "nuclear suppliers group": 16,
      "look east policy": 12,
      "act east policy": 12,
      "india neighbourhood": 14,
      "nuclear non-proliferation": 14,
      "india china relations": 12,
      "india us relations": 12,
    },
    rareKeywordWeights: {
      "bimstec": 16,
      "brics": 14,
      "quad": 14,
      "asean": 12,
      "unsc": 14,
      "nato": 12,
      "saarc": 12,
      "g20": 10,
      "npt": 12,
      "ctbt": 12,
    },
    keywordWeights: {
      "imf": 7,
      "wto": 7,
      "treaty": 5,
      "summit": 4,
      "geopolitics": 7,
      "diplomacy": 5,
      "sanctions": 6,
      "bilateral": 7,
    },
  },

  "Society": {
    phraseWeights: {
      "women empowerment": 14,
      "social justice": 12,
      "caste discrimination": 14,
      "scheduled caste": 12,
      "scheduled tribe": 12,
      "poverty alleviation": 12,
      "communal harmony": 12,
      "reservation policy": 14,
      "demographic dividend": 14,
    },
    rareKeywordWeights: {
      "dalit": 12,
      "adivasi": 12,
      "obc": 12,
      "secularism": 10,
      "communalism": 12,
      "regionalism": 10,
    },
    keywordWeights: {
      "caste": 7,
      "tribe": 6,
      "women": 5,
      "poverty": 6,
      "urbanization": 7,
      "globalization": 6,
      "diversity": 5,
      "minority": 6,
      "gender": 6,
    },
  },

  "Current Affairs": {
    phraseWeights: {
      "places in news": 14,
      "government scheme": 10,
      "awards personality": 10,
      "current affairs": 14,
    },
    rareKeywordWeights: {
      "news": 4,
      "recent": 4,
    },
    keywordWeights: {
      "scheme": 4,
      "award": 4,
      "report": 3,
      "index": 3,
    },
  },
};

// ─── SECTION KEYWORD BANKS V2 (three-tier per section) ───────────────────────

export const SECTION_KEYWORDS = {

  "Polity": {
    "Fundamental Rights": {
      phraseWeights: {
        "fundamental rights": 20,
        "article 19": 20,
        "article 21": 18,
        "article 14": 16,
        "article 32": 18,
        "right to equality": 16,
        "right to freedom": 16,
        "reasonable restriction": 18,
        "writ jurisdiction": 16,
        "habeas corpus": 16,
        "right to constitutional remedies": 16,
        "freedom of speech": 14,
        "freedom of religion": 14,
      },
      rareKeywordWeights: { "writ": 12, "mandamus": 12, "certiorari": 14 },
      keywordWeights: { "rights": 6, "fundamental": 8, "freedoms": 7, "restriction": 7 },
    },
    "DPSP and Fundamental Duties": {
      phraseWeights: {
        "directive principles": 18,
        "dpsp": 18,
        "fundamental duties": 18,
        "article 51a": 14,
        "article 36": 12,
      },
      rareKeywordWeights: { "dpsp": 18, "directive": 10 },
      keywordWeights: { "duties": 6, "principles": 5 },
    },
    "Preamble and Key Features": {
      phraseWeights: {
        "preamble": 18,
        "features of constitution": 16,
        "sovereign socialist": 16,
        "federal unitary": 14,
      },
      rareKeywordWeights: { "preamble": 18, "sovereign": 10 },
      keywordWeights: { "secular": 7, "democratic": 5 },
    },
    "Executive": {
      phraseWeights: {
        "president of india": 16,
        "prime minister": 12,
        "council of ministers": 14,
        "ordinance power": 14,
        "cabinet": 10,
      },
      rareKeywordWeights: { "ordinance": 12, "prorogation": 14 },
      keywordWeights: { "president": 7, "executive": 7, "cabinet": 6 },
    },
    "State Executive": {
      phraseWeights: { "governor": 14, "chief minister": 12, "state council": 10 },
      rareKeywordWeights: {},
      keywordWeights: { "governor": 12, "chief": 5 },
    },
    "Parliament and Legislature": {
      phraseWeights: {
        "lok sabha": 16,
        "rajya sabha": 16,
        "joint session": 14,
        "money bill": 14,
        "legislative process": 12,
      },
      rareKeywordWeights: { "dissolution": 12, "prorogation": 12 },
      keywordWeights: { "parliament": 10, "lok": 8, "rajya": 8, "speaker": 7, "bill": 5 },
    },
    "Judiciary": {
      phraseWeights: {
        "supreme court": 16,
        "high court": 12,
        "judicial review": 16,
        "judicial activism": 14,
        "public interest litigation": 16,
        "pil": 14,
        "curative petition": 14,
      },
      rareKeywordWeights: { "pil": 14, "certiorari": 14, "mandamus": 12 },
      keywordWeights: { "judiciary": 12, "court": 6, "judge": 6 },
    },
    "Federalism and Center-State Relations": {
      phraseWeights: {
        "center state": 16,
        "federalism": 16,
        "seventh schedule": 16,
        "inter-state council": 14,
        "union list": 14,
        "state list": 14,
        "concurrent list": 14,
      },
      rareKeywordWeights: { "federalism": 14 },
      keywordWeights: { "center": 5, "federal": 8 },
    },
    "Constitutional Bodies": {
      phraseWeights: {
        "election commission": 16,
        "cag": 16,
        "finance commission": 14,
        "attorney general": 12,
        "upsc": 12,
      },
      rareKeywordWeights: { "cag": 16, "upsc": 12, "lokpal": 14 },
      keywordWeights: { "commission": 5, "constitutional": 5 },
    },
    "Elections": {
      phraseWeights: {
        "model code of conduct": 14,
        "electoral roll": 14,
        "delimitation commission": 14,
        "evms": 12,
        "election commission": 12,
      },
      rareKeywordWeights: { "evm": 12, "delimitation": 14, "electoral": 10 },
      keywordWeights: { "election": 12, "vote": 6 },
    },
    "Emergency Provisions": {
      phraseWeights: {
        "national emergency": 18,
        "president rule": 18,
        "financial emergency": 16,
        "article 356": 16,
        "article 352": 16,
      },
      rareKeywordWeights: { "proclamation": 12 },
      keywordWeights: { "emergency": 14 },
    },
    "Amendments": {
      phraseWeights: { "constitutional amendment": 18, "article 368": 16 },
      rareKeywordWeights: {},
      keywordWeights: { "amendment": 12 },
    },
    "Citizenship": {
      phraseWeights: { "citizenship act": 14, "overseas citizen": 12 },
      rareKeywordWeights: { "nri": 8 },
      keywordWeights: { "citizenship": 14, "citizen": 8 },
    },
    "Local Self Government": {
      phraseWeights: {
        "panchayati raj": 18,
        "73rd amendment": 18,
        "74th amendment": 18,
        "gram sabha": 14,
        "urban local bodies": 14,
      },
      rareKeywordWeights: {},
      keywordWeights: { "panchayat": 14, "municipality": 12, "gram": 8 },
    },
    "Governance": {
      phraseWeights: { "e-governance": 12, "good governance": 12, "niti aayog": 14 },
      rareKeywordWeights: {},
      keywordWeights: { "governance": 8, "transparency": 6, "accountability": 6 },
    },
  },

  "Economy": {
    "Banking Structure": {
      phraseWeights: {
        "commercial bank": 16,
        "scheduled bank": 14,
        "cooperative bank": 14,
        "priority sector lending": 16,
        "banking regulation": 14,
        "npa": 16,
        "asset quality": 14,
      },
      rareKeywordWeights: { "npa": 16, "nbfc": 12 },
      keywordWeights: { "banking": 10, "bank": 5, "credit": 6 },
    },
    "Monetary Policy and RBI": {
      phraseWeights: {
        "repo rate": 20,
        "reverse repo": 18,
        "monetary policy": 18,
        "monetary policy committee": 20,
        "open market operations": 16,
        "statutory liquidity ratio": 16,
        "cash reserve ratio": 16,
      },
      rareKeywordWeights: { "rbi": 14, "mpc": 18, "repo": 14, "slr": 12, "crr": 12 },
      keywordWeights: { "liquidity": 8, "monetary": 10, "inflation": 8 },
    },
    "Inflation and Price Indices": {
      phraseWeights: {
        "consumer price index": 16,
        "wholesale price index": 16,
        "core inflation": 16,
        "headline inflation": 14,
        "food inflation": 12,
      },
      rareKeywordWeights: { "cpi": 14, "wpi": 12 },
      keywordWeights: { "inflation": 12, "prices": 5, "deflation": 8 },
    },
    "Budget and Fiscal Policy": {
      phraseWeights: {
        "fiscal deficit": 16,
        "revenue deficit": 14,
        "public expenditure": 12,
        "fiscal consolidation": 14,
        "frbm act": 16,
        "budget estimate": 14,
      },
      rareKeywordWeights: { "frbm": 16 },
      keywordWeights: { "budget": 12, "fiscal": 10, "deficit": 8, "expenditure": 5 },
    },
    "Taxation": {
      phraseWeights: {
        "goods and services tax": 16,
        "gst council": 16,
        "direct tax": 14,
        "income tax": 12,
        "corporate tax": 12,
      },
      rareKeywordWeights: { "gst": 16, "cess": 10 },
      keywordWeights: { "tax": 8, "taxation": 10, "surcharge": 7 },
    },
    "Financial Markets and Capital Market": {
      phraseWeights: {
        "capital market": 16,
        "stock exchange": 14,
        "mutual fund": 14,
        "bond market": 12,
        "ipo": 12,
      },
      rareKeywordWeights: { "sebi": 14, "nse": 12, "bse": 12 },
      keywordWeights: { "market": 4, "capital": 5, "securities": 8, "equity": 7 },
    },
    "External Sector and BOP": {
      phraseWeights: {
        "balance of payments": 18,
        "current account": 14,
        "capital account": 12,
        "forex reserves": 16,
        "exchange rate": 14,
        "trade deficit": 14,
      },
      rareKeywordWeights: { "bop": 16, "forex": 14, "cad": 14 },
      keywordWeights: { "export": 5, "import": 5 },
    },
    "Growth, Development and Planning": {
      phraseWeights: {
        "economic growth": 12,
        "gdp growth": 14,
        "niti aayog": 14,
        "human development": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "gdp": 10, "growth": 6, "development": 5, "planning": 7 },
    },
    "Agriculture Sector": {
      phraseWeights: {
        "minimum support price": 16,
        "msp": 16,
        "crop insurance": 14,
        "agricultural credit": 14,
      },
      rareKeywordWeights: { "msp": 16, "kisan": 10 },
      keywordWeights: { "agriculture": 12, "farmer": 6, "crop": 6 },
    },
    "Infrastructure and Energy": {
      phraseWeights: {
        "infrastructure development": 12,
        "renewable energy": 12,
        "national highway": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "infrastructure": 10, "energy": 6, "power": 5, "highway": 8 },
    },
    "Poverty and Inclusion": {
      phraseWeights: {
        "poverty line": 16,
        "financial inclusion": 14,
        "jan dhan": 14,
        "welfare scheme": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "poverty": 12, "inclusion": 8, "welfare": 7 },
    },
  },

  "Environment": {
    "Biodiversity": {
      phraseWeights: {
        "biodiversity hotspot": 20,
        "endemic species": 18,
        "megadiverse": 16,
        "biological diversity": 16,
        "genetic diversity": 14,
        "species richness": 14,
      },
      rareKeywordWeights: { "endemic": 14, "megadiverse": 14 },
      keywordWeights: { "biodiversity": 14, "species": 7, "habitat": 6 },
    },
    "Climate Change": {
      phraseWeights: {
        "global warming": 16,
        "greenhouse gas": 16,
        "carbon emission": 16,
        "paris agreement": 16,
        "unfccc": 14,
        "ipcc report": 14,
      },
      rareKeywordWeights: { "ipcc": 14, "ghg": 12, "unfccc": 14 },
      keywordWeights: { "climate": 8, "warming": 7, "carbon": 7 },
    },
    "Ecology Concepts": {
      phraseWeights: {
        "food web": 16,
        "food chain": 16,
        "trophic level": 16,
        "ecological succession": 16,
        "energy flow": 14,
        "nutrient cycle": 14,
      },
      rareKeywordWeights: { "trophic": 14, "succession": 12 },
      keywordWeights: { "ecology": 12, "ecosystem": 10 },
    },
    "Environmental Pollution": {
      phraseWeights: {
        "air pollution": 14,
        "water pollution": 14,
        "soil contamination": 14,
        "particulate matter": 16,
        "pm2.5": 16,
      },
      rareKeywordWeights: { "smog": 10, "effluent": 12 },
      keywordWeights: { "pollution": 12, "contamination": 8 },
    },
    "Conservation and Protected Areas": {
      phraseWeights: {
        "national park": 16,
        "wildlife sanctuary": 16,
        "biosphere reserve": 16,
        "tiger reserve": 16,
        "project tiger": 16,
        "community reserve": 14,
        "protected area": 16,
      },
      rareKeywordWeights: { "sanctuary": 12 },
      keywordWeights: { "conservation": 8, "reserve": 7, "protected": 8 },
    },
    "Environmental Legislation and Acts": {
      phraseWeights: {
        "environment protection act": 16,
        "forest conservation act": 16,
        "wildlife protection act": 16,
        "eia notification": 14,
        "coastal regulation zone": 16,
      },
      rareKeywordWeights: { "eia": 14 },
      keywordWeights: { "act": 4, "legislation": 5, "notification": 4 },
    },
    "International Environmental Conventions": {
      phraseWeights: {
        "ramsar convention": 18,
        "cites": 18,
        "cbd convention": 16,
        "stockholm convention": 16,
        "minamata": 16,
        "nagoya protocol": 16,
        "paris agreement": 14,
      },
      rareKeywordWeights: { "ramsar": 18, "cites": 18, "cbd": 14 },
      keywordWeights: { "convention": 6 },
    },
    "Species Conservation": {
      phraseWeights: {
        "endangered species": 16,
        "iucn red list": 18,
        "critically endangered": 16,
        "invasive species": 14,
      },
      rareKeywordWeights: { "iucn": 16, "endangered": 12 },
      keywordWeights: { "species": 6 },
    },
  },

  "Science & Technology": {
    "Biotechnology": {
      phraseWeights: {
        "gene editing": 20,
        "crispr cas9": 20,
        "recombinant dna": 16,
        "genetically modified": 16,
        "stem cell": 16,
        "cloning": 14,
        "monoclonal antibody": 18,
        "vaccine development": 14,
      },
      rareKeywordWeights: { "crispr": 18, "gmo": 12, "genome": 14, "dna": 10 },
      keywordWeights: { "biotechnology": 10, "gene": 8, "vaccine": 7 },
    },
    "Space": {
      phraseWeights: {
        "geostationary orbit": 20,
        "polar orbit": 14,
        "launch vehicle": 16,
        "pslv": 16,
        "gslv": 16,
        "chandrayaan": 18,
        "mangalyaan": 18,
        "space station": 14,
        "reusable launch": 14,
      },
      rareKeywordWeights: { "isro": 18, "pslv": 16, "gslv": 14, "chandrayaan": 18 },
      keywordWeights: { "satellite": 8, "orbit": 7, "launch": 6 },
    },
    "Nuclear Technology": {
      phraseWeights: {
        "nuclear fission": 16,
        "nuclear fusion": 16,
        "nuclear reactor": 16,
        "atomic energy": 14,
        "nuclear non-proliferation": 16,
        "npt": 14,
      },
      rareKeywordWeights: { "npt": 14, "fission": 14, "atom": 10 },
      keywordWeights: { "nuclear": 12, "reactor": 10 },
    },
    "AI and Emerging Technology": {
      phraseWeights: {
        "artificial intelligence": 16,
        "machine learning": 16,
        "deep learning": 16,
        "quantum computing": 16,
        "nanotechnology": 16,
        "robotics": 14,
      },
      rareKeywordWeights: { "quantum": 12, "nano": 12, "semiconductor": 14 },
      keywordWeights: { "ai": 7, "robot": 7 },
    },
    "Health and Diseases": {
      phraseWeights: {
        "communicable disease": 14,
        "vaccine development": 14,
        "antimicrobial resistance": 16,
        "public health": 12,
        "disease surveillance": 12,
        "monoclonal antibody": 16,
      },
      rareKeywordWeights: {},
      keywordWeights: { "disease": 5, "vaccine": 7, "health": 4, "virus": 6, "bacteria": 6 },
    },
    "IT and Communications": {
      phraseWeights: {
        "5g technology": 16,
        "internet of things": 16,
        "blockchain": 14,
        "cybersecurity": 16,
        "data privacy": 14,
      },
      rareKeywordWeights: { "5g": 14, "blockchain": 12, "cyber": 12 },
      keywordWeights: { "internet": 5, "data": 4 },
    },
    "Defence Technology": {
      phraseWeights: {
        "ballistic missile": 16,
        "agni missile": 16,
        "drdo": 16,
        "hypersonic": 14,
        "stealth technology": 14,
      },
      rareKeywordWeights: { "drdo": 16, "missile": 12 },
      keywordWeights: { "defence": 10, "radar": 7, "sonar": 7 },
    },
  },

  "Geography": {
    "Indian Physiography": {
      phraseWeights: {
        "himalayan ranges": 14,
        "indo gangetic plain": 16,
        "deccan plateau": 14,
        "physiographic division": 16,
        "western ghats": 12,
        "eastern ghats": 12,
      },
      rareKeywordWeights: { "physiography": 14 },
      keywordWeights: { "himalaya": 8, "plateau": 8, "ghats": 8 },
    },
    "Indian Climate and Monsoon": {
      phraseWeights: {
        "southwest monsoon": 18,
        "northeast monsoon": 16,
        "indian monsoon": 16,
        "monsoon withdrawal": 14,
        "el nino": 14,
        "la nina": 14,
        "western disturbance": 18,
        "rainfall distribution": 14,
      },
      rareKeywordWeights: { "monsoon": 16 },
      keywordWeights: { "rainfall": 8, "climate": 5 },
    },
    "Rivers and Drainage": {
      phraseWeights: {
        "river basin": 14,
        "drainage pattern": 16,
        "river interlinking": 14,
        "tributaries": 12,
        "watershed": 12,
      },
      rareKeywordWeights: { "drainage": 14 },
      keywordWeights: { "river": 10, "tributary": 8, "basin": 7 },
    },
    "Physical Geography - Geomorphology": {
      phraseWeights: {
        "plate tectonics": 18,
        "rock cycle": 16,
        "earthquake zone": 14,
        "volcanic eruption": 14,
        "landforms": 12,
      },
      rareKeywordWeights: { "landform": 14 },
      keywordWeights: { "earthquake": 10, "volcano": 10, "plate": 8, "rock": 5 },
    },
    "Physical Geography - Climatology": {
      phraseWeights: {
        "koppen classification": 16,
        "pressure belt": 14,
        "trade winds": 14,
        "jet stream": 14,
        "atmosphere layer": 12,
        "western disturbance": 16,
      },
      rareKeywordWeights: { "climatology": 14 },
      keywordWeights: { "atmosphere": 8, "pressure": 7, "wind": 6 },
    },
    "Oceanography": {
      phraseWeights: {
        "ocean current": 16,
        "continental shelf": 16,
        "exclusive economic zone": 16,
        "eez": 14,
        "ocean salinity": 14,
      },
      rareKeywordWeights: { "eez": 14, "salinity": 12 },
      keywordWeights: { "ocean": 10, "current": 5, "tidal": 8 },
    },
    "Indian Agriculture and Resources": {
      phraseWeights: {
        "soil type": 14,
        "cropping pattern": 14,
        "mineral resources": 14,
      },
      rareKeywordWeights: {},
      keywordWeights: { "soil": 8, "agriculture": 7, "mineral": 8, "resources": 5 },
    },
    "World Geography - Maps and Locations": {
      phraseWeights: {
        "strategic location": 12,
        "strait": 14,
        "chokepoint": 14,
      },
      rareKeywordWeights: { "strait": 12 },
      keywordWeights: { "location": 4, "places": 4, "maps": 5 },
    },
  },

  "Ancient Indian History": {
    "Prehistoric and IVC": {
      phraseWeights: {
        "indus valley civilisation": 20,
        "harappan": 20,
        "mohenjodaro": 18,
        "prehistoric india": 16,
        "neolithic age": 14,
      },
      rareKeywordWeights: { "harappa": 18, "ivc": 18, "prehistoric": 14, "neolithic": 12 },
      keywordWeights: {},
    },
    "Vedic Period": {
      phraseWeights: {
        "rig veda": 18,
        "vedic period": 16,
        "later vedic": 14,
        "upanishad": 14,
      },
      rareKeywordWeights: { "vedic": 16, "veda": 12, "upanishad": 12, "aryan": 10 },
      keywordWeights: {},
    },
    "Mauryan Empire": {
      phraseWeights: {
        "mauryan empire": 18,
        "ashoka edicts": 18,
        "chandragupta maurya": 16,
        "arthashastra": 16,
      },
      rareKeywordWeights: { "maurya": 16, "ashoka": 14, "arthashastra": 14 },
      keywordWeights: { "chandragupta": 10 },
    },
    "Post-Mauryan to Gupta": {
      phraseWeights: {
        "gupta empire": 16,
        "kushana": 14,
        "satavahana": 14,
        "post mauryan": 14,
      },
      rareKeywordWeights: { "gupta": 14, "harsha": 12 },
      keywordWeights: {},
    },
    "Sangam Age": {
      phraseWeights: { "sangam age": 18, "sangam literature": 16, "tamil sangam": 16 },
      rareKeywordWeights: { "sangam": 18 },
      keywordWeights: { "tamil": 5 },
    },
    "Religion and Philosophy - Ancient": {
      phraseWeights: {
        "early buddhism": 14,
        "mahayana": 14,
        "theravada": 14,
        "jainism": 14,
      },
      rareKeywordWeights: { "mahavira": 12, "siddhartha": 10 },
      keywordWeights: { "buddhism": 12, "jain": 10 },
    },
  },

  "Medieval Indian History": {
    "Delhi Sultanate": {
      phraseWeights: {
        "delhi sultanate": 20,
        "iqta system": 20,
        "slave dynasty": 16,
        "khilji dynasty": 16,
        "tughlaq dynasty": 16,
        "lodhi dynasty": 14,
        "administrative system": 12,
      },
      rareKeywordWeights: { "sultanate": 16, "iqta": 18, "khilji": 12, "tughlaq": 12 },
      keywordWeights: { "slave": 7 },
    },
    "Mughal Empire": {
      phraseWeights: {
        "mughal empire": 18,
        "mansabdari system": 18,
        "jagir": 16,
        "din ilahi": 14,
        "akbar": 14,
      },
      rareKeywordWeights: { "mughal": 16, "mansab": 14, "aurangzeb": 10, "babur": 10 },
      keywordWeights: {},
    },
    "Bhakti and Sufi Movements": {
      phraseWeights: { "bhakti movement": 18, "sufi movement": 18, "sufi order": 16 },
      rareKeywordWeights: { "bhakti": 16, "sufi": 16, "kabir": 10 },
      keywordWeights: {},
    },
    "Vijayanagara and Regional": {
      phraseWeights: {
        "vijayanagara empire": 18,
        "regional kingdoms": 14,
        "chola empire": 14,
      },
      rareKeywordWeights: { "vijayanagara": 16, "chola": 12 },
      keywordWeights: { "regional": 5 },
    },
    "Art and Architecture - Medieval": {
      phraseWeights: {
        "indo islamic architecture": 16,
        "mughal painting": 14,
      },
      rareKeywordWeights: {},
      keywordWeights: { "architecture": 6, "painting": 5, "literature": 5 },
    },
  },

  "Modern Indian History": {
    "Advent of Europeans": {
      phraseWeights: {
        "british east india company": 16,
        "advent of europeans": 16,
      },
      rareKeywordWeights: { "portuguese": 10, "dutch": 8 },
      keywordWeights: { "european": 8, "company": 7, "british": 5, "colonial": 6 },
    },
    "Revolt of 1857": {
      phraseWeights: {
        "revolt of 1857": 18,
        "sepoy mutiny": 16,
        "first war of independence": 16,
      },
      rareKeywordWeights: { "1857": 18, "sepoy": 12, "mutiny": 12 },
      keywordWeights: { "revolt": 10 },
    },
    "Nationalist Movement": {
      phraseWeights: {
        "non cooperation": 16,
        "civil disobedience": 16,
        "quit india": 18,
        "salt march": 16,
        "indian national congress": 14,
        "freedom struggle": 14,
      },
      rareKeywordWeights: { "satyagraha": 12, "swadeshi": 12, "gandhi": 10 },
      keywordWeights: { "nehru": 7, "congress": 6, "moderates": 10, "extremists": 10 },
    },
    "Social Reforms": {
      phraseWeights: {
        "social reform": 16,
        "brahmo samaj": 16,
        "arya samaj": 16,
        "ram mohan roy": 16,
        "sati abolition": 14,
      },
      rareKeywordWeights: { "samaj": 12 },
      keywordWeights: { "reform": 7, "reformer": 10 },
    },
    "Governor Generals and Administration": {
      phraseWeights: {
        "governor general": 16,
        "viceroy": 14,
        "lord dalhousie": 14,
        "doctrine of lapse": 16,
        "british administration": 12,
      },
      rareKeywordWeights: { "dalhousie": 12 },
      keywordWeights: { "viceroy": 10, "governor": 6, "administration": 5 },
    },
    "Constitutional Development": {
      phraseWeights: {
        "government of india act": 16,
        "morley minto": 16,
        "montagu chelmsford": 16,
      },
      rareKeywordWeights: { "montagu": 12, "morley": 10 },
      keywordWeights: { "constitutional": 6, "reforms": 5 },
    },
    "Partition and Independence": {
      phraseWeights: {
        "cabinet mission": 18,
        "mountbatten plan": 18,
        "partition of india": 16,
        "Indian independence act": 14,
      },
      rareKeywordWeights: { "mountbatten": 14 },
      keywordWeights: { "partition": 10, "independence": 6 },
    },
  },

  "Art & Culture": {
    "Architecture": {
      phraseWeights: {
        "temple architecture": 16,
        "stupa": 16,
        "ajanta caves": 16,
        "ellora caves": 16,
        "rock cut": 14,
        "nagara style": 14,
        "dravidian style": 14,
      },
      rareKeywordWeights: { "stupa": 14, "ajanta": 14, "ellora": 14 },
      keywordWeights: { "architecture": 12, "temple": 10, "cave": 10 },
    },
    "Painting": {
      phraseWeights: {
        "miniature painting": 16,
        "mughal painting": 14,
        "rajput painting": 14,
        "cave painting": 16,
        "ajanta painting": 14,
      },
      rareKeywordWeights: { "miniature": 12, "fresco": 12 },
      keywordWeights: { "painting": 12 },
    },
    "Sculpture": {
      phraseWeights: { "bronze sculpture": 14, "stone carving": 12 },
      rareKeywordWeights: {},
      keywordWeights: { "sculpture": 12, "carving": 8 },
    },
    "Performing Arts": {
      phraseWeights: {
        "classical dance": 16,
        "bharatanatyam": 16,
        "kathak": 14,
        "carnatic music": 14,
        "hindustani music": 14,
        "folk dance": 12,
      },
      rareKeywordWeights: { "bharatanatyam": 16, "kathak": 14 },
      keywordWeights: { "dance": 12, "music": 8, "theatre": 8, "puppet": 8 },
    },
    "Literature and Language": {
      phraseWeights: {
        "classical literature": 14,
        "pali text": 14,
        "sanskrit literature": 14,
      },
      rareKeywordWeights: {},
      keywordWeights: { "literature": 10, "language": 5 },
    },
    "Religion and Philosophy": {
      phraseWeights: {
        "vedanta philosophy": 14,
        "samkhya philosophy": 12,
        "yoga philosophy": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "religion": 7, "philosophy": 7, "dharma": 8 },
    },
  },

  "International Relations": {
    "International Organisations": {
      phraseWeights: {
        "united nations": 14,
        "world bank": 14,
        "security council": 16,
        "international court": 14,
      },
      rareKeywordWeights: { "unsc": 14, "imf": 10, "wto": 10 },
      keywordWeights: { "un": 5, "who": 6 },
    },
    "Regional Groupings": {
      phraseWeights: {
        "brics": 16,
        "saarc": 16,
        "asean": 16,
        "bimstec": 18,
        "quad": 16,
        "g20 summit": 14,
        "nato": 14,
      },
      rareKeywordWeights: { "bimstec": 18, "brics": 14, "quad": 14, "asean": 12, "saarc": 12 },
      keywordWeights: { "grouping": 5, "summit": 4 },
    },
    "India's Neighbours": {
      phraseWeights: {
        "india china": 14,
        "india pakistan": 14,
        "india nepal": 12,
        "india bangladesh": 12,
        "neighbourhood policy": 14,
      },
      rareKeywordWeights: { "neighbour": 12 },
      keywordWeights: { "bilateral": 7, "china": 5, "pakistan": 5 },
    },
    "Major Powers": {
      phraseWeights: {
        "india us relations": 14,
        "india russia": 12,
        "strategic partnership": 14,
      },
      rareKeywordWeights: { "superpower": 10 },
      keywordWeights: { "usa": 7, "russia": 7, "strategic": 6 },
    },
    "Climate and Disarmament": {
      phraseWeights: {
        "nuclear non-proliferation": 16,
        "npt": 14,
        "ctbt": 14,
        "disarmament": 16,
      },
      rareKeywordWeights: { "npt": 14, "ctbt": 14 },
      keywordWeights: { "disarmament": 12, "treaty": 7 },
    },
  },

  "Society": {
    "Social Issues and Empowerment": {
      phraseWeights: {
        "social empowerment": 14,
        "scheduled castes": 14,
        "scheduled tribes": 14,
        "other backward classes": 14,
        "reservation policy": 14,
      },
      rareKeywordWeights: { "dalit": 12, "obc": 12 },
      keywordWeights: { "empowerment": 8, "reservation": 8 },
    },
    "Women Empowerment": {
      phraseWeights: {
        "women empowerment": 18,
        "gender equality": 16,
        "domestic violence": 14,
        "maternity benefit": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "women": 10, "gender": 10, "girl": 6 },
    },
    "Tribal Issues": {
      phraseWeights: { "tribal rights": 16, "forest rights act": 16, "adivasi": 16 },
      rareKeywordWeights: { "adivasi": 14, "tribal": 12 },
      keywordWeights: {},
    },
    "Population and Urbanization": {
      phraseWeights: {
        "census data": 14,
        "demographic dividend": 16,
        "urbanization rate": 14,
        "migration pattern": 12,
      },
      rareKeywordWeights: {},
      keywordWeights: { "population": 10, "census": 10, "urban": 6, "migration": 6 },
    },
  },
};
