import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { normalizePyqRecord } from "../brain/normalizePyqRecord.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ── Paths ─────────────────────────────────────────────────────────────────────
const DATA_DIR        = path.resolve(__dirname, "../data");
// Source: v2 folder-based dataset (includes csat subfolder)
const PYQ_V2_DIR      = path.join(DATA_DIR, "pyq_questions_v2", "prelims");
const OUTPUT_DIR      = path.join(DATA_DIR, "pyq_index");

// ── Exclusion filter ──────────────────────────────────────────────────────────
// Skip metadata, aggregate, and report files generated by the build pipeline.
const META_FILE_RE = /(_master|_report|_index|_by_node|_all_topics|_production|_perfection|_zero_ambiguity)/i;

// ── CSAT module → canonical syllabusNodeId ────────────────────────────────────
// v2 CSAT questions carry no nodeId; we assign based on the module field.
const CSAT_MODULE_TO_NODE = {
  "Logical Reasoning":     "CSAT-LR",
  "Reasoning":             "CSAT-LR",
  "Quantitative Aptitude": "CSAT-BN",
  "Basic Numeracy":        "CSAT-BN",
  "Mathematics":           "CSAT-BN",
  "Reading Comprehension": "CSAT-RC",
  "Comprehension":         "CSAT-RC",
  "Data Interpretation":   "CSAT-DI",
  "Decision Making":       "CSAT-DS",
};

function deriveCsatNodeId(qModule, metaModule) {
  return CSAT_MODULE_TO_NODE[(qModule || "").trim()]
      || CSAT_MODULE_TO_NODE[(metaModule || "").trim()]
      || "CSAT-LR"; // safest fallback
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function ensureDir(dirPath) {
  try { await fs.mkdir(dirPath, { recursive: true }); } catch { /* exists */ }
}

async function findJsonFiles(dir, fileList = []) {
  const items = await fs.readdir(dir, { withFileTypes: true });
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      await findJsonFiles(fullPath, fileList);
    } else if (item.isFile() && item.name.endsWith(".json") && !META_FILE_RE.test(item.name)) {
      fileList.push({ path: fullPath, name: item.name });
    }
  }
  return fileList;
}

// ── Payload extraction ────────────────────────────────────────────────────────
// Supports:
//   1. Direct array          → [ { id, question, ... }, ... ]
//   2. Wrapped object        → { questions: [...], subject?, module?, ... }
//   3. RC nested schema      → { years: [ { year, sets: [ { questions: [...] } ] } ] }
//   4. Topics array          → { topics: [...] }

function extractFromPayload(parsed) {
  if (Array.isArray(parsed)) {
    return { questions: parsed, meta: {} };
  }

  if (parsed && Array.isArray(parsed.years)) {
    // Reading Comprehension nested format
    const { years, ...meta } = parsed;
    const questions = [];
    for (const yearObj of years) {
      for (const setObj of (yearObj.sets || [])) {
        for (const q of (setObj.questions || [])) {
          questions.push({
            ...q,
            id:   q.id || q.questionId || undefined,
            year: q.year || yearObj.year,
          });
        }
      }
    }
    return { questions, meta };
  }

  if (parsed && Array.isArray(parsed.questions)) {
    const { questions, ...meta } = parsed;
    return { questions, meta };
  }

  if (parsed && Array.isArray(parsed.topics)) {
    return { questions: parsed.topics, meta: {} };
  }

  return { questions: [], meta: {} };
}

// ── Dedup tracking ────────────────────────────────────────────────────────────

function fingerprint(q) {
  const text = (q.question || q.questionText || "")
    .toLowerCase().replace(/\s+/g, " ").trim().slice(0, 80);
  return `${q.year ?? "?"}|${q.questionNumber ?? "?"}|${text}`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function buildMasterIndex() {
  await ensureDir(OUTPUT_DIR);

  console.log("🔍 Scanning for PYQ JSONs in:", PYQ_V2_DIR);
  const files = await findJsonFiles(PYQ_V2_DIR);
  console.log(`   Found ${files.length} candidate files.`);

  const masterIndex = {};
  const seenIds          = new Set();
  const seenFingerprints = new Set();

  let totalQuestions = 0;
  let csatQuestions  = 0;
  let autoIds        = 0;

  for (const fileObj of files) {
    const isCsatFile = fileObj.path.replace(/\\/g, "/").includes("/csat/");

    let raw;
    try {
      raw = await fs.readFile(fileObj.path, "utf-8");
    } catch (e) {
      console.error(`❌ Cannot read ${fileObj.name}:`, e.message);
      continue;
    }

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch (e) {
      console.error(`❌ JSON parse error in ${fileObj.name}:`, e.message);
      continue;
    }

    const { questions, meta } = extractFromPayload(parsed);
    if (!questions.length) continue;

    for (const q of questions) {
      if (!q || typeof q !== "object") continue;

      // ── Inject stage/paper/nodeId BEFORE normalization ─────────────────────
      // v2 questions don't carry stage/paper; derive from folder position.
      const enriched = {
        ...q,
        // Stage: always "Prelims" for everything in pyq_questions_v2/prelims/
        stage: q.stage || "Prelims",
        // Paper: "CSAT" for csat subfolder, "GS" for everything else
        paper: q.paper || (isCsatFile ? "CSAT" : "GS"),
        // CSAT nodeId: assign if missing (all v2 CSAT questions lack nodeId)
        syllabusNodeId:
          q.syllabusNodeId || q.nodeId ||
          (isCsatFile ? deriveCsatNodeId(q.module, meta.module) : null),
        // RC questions use questionId instead of id
        id: q.id || q.questionId || undefined,
      };

      // ── Dedup ──────────────────────────────────────────────────────────────
      const tentativeId = enriched.id;
      if (tentativeId) {
        if (seenIds.has(tentativeId)) continue;
        // Will finalize after normalization
      } else {
        const fp = fingerprint(enriched);
        if (seenFingerprints.has(fp)) continue;
        seenFingerprints.add(fp);
      }

      // ── Normalize ──────────────────────────────────────────────────────────
      const normalized = normalizePyqRecord(enriched, fileObj);

      // If normalizePyqRecord generated a fallback ID, check it hasn't collided
      if (!tentativeId && seenIds.has(normalized.id)) continue;

      if (!tentativeId) autoIds++;
      seenIds.add(normalized.id);

      masterIndex[normalized.id] = normalized;
      totalQuestions++;

      if (normalized.stage === "csat") csatQuestions++;
    }
  }

  const outputPath = path.join(OUTPUT_DIR, "pyq_master_index.json");
  await fs.writeFile(outputPath, JSON.stringify(masterIndex, null, 2), "utf-8");

  console.log("\n✅ Master Index Built!");
  console.log(`[PYQ BUILD] Total Questions Indexed: ${totalQuestions} (Unique IDs: ${Object.keys(masterIndex).length})`);
  console.log(`[PYQ BUILD] Total CSAT: ${csatQuestions}`);
  if (autoIds > 0) {
    console.log(`[PYQ BUILD] Auto-assigned IDs: ${autoIds} (questions had no id field)`);
  }
}

buildMasterIndex().catch(e => {
  console.error("Fatal error during buildMasterIndex:", e);
  process.exit(1);
});
