// backend/brain/pyqNodeAliasMap.js
export const PYQ_NODE_ALIAS_MAP = {
  "GS2-POL-FED": "GS2-POL-CSREL",
  "GS2-POL-GOV": "GS2-GOV-GOOD-GOV",
  "GS2-POL-CONTEMP": "GS2-POL-PARL",
  "GS2-IR-CONTEMP": "GS2-IR-INSTITUTIONS",
  "GS3-ST-MATERIALS": "GS3-ST-MATERIALS-NANO-ROBOTICS-AI",
  "GS3-ST-ENERGY": "GS3-ENV-ENERGY",
  "GS3-ST-CYBERSECURITY": "GS3-SEC-CYBER-BASICS",
  "GS3-ST-QUANTUM": "GS3-ST-IT-COMM",
  "GS3-ST-AI": "GS3-ST-MATERIALS-NANO-ROBOTICS-AI",
  "GS3-ST-ENV-TECH": "GS3-ENV-CONSERVATION",
  "GS3-ST-INFRA-TRANSPORT-TECH": "GS3-ECO-SECT-INFRA",
  "GS3-ENV-MAINS": "GS3-ENV-CONSERVATION",
  "GS3-ENV-RESOURCES": "GS3-ENV-LAND-WATER",
  "GS3-SEC-CONTEMP": "GS3-SEC-TERRORISM",
  "GS1-HIS-WORLD-INDUSTRIAL": "GS1-HIS-WORLD-REV",
  "CSAT-DM": "CSAT-LR-MISC",
  "GS3-ST-BASIC-SCIENCE": "GS3-ST-GENSCI-BIO"
};
